list all database

diff --git a/centos7/menu/list_databases b/centos7/menu/list_databases
--- a/centos7/menu/list_databases
+++ b/centos7/menu/list_databases
@@ -377,6 +377,19 @@ get_list_databases(){
     fi  
 }
 
+get_list_databases2(){
+    echo " - Dropping test database..."
+    while read -r line
+    do
+        echo "$line"
+    done <<< $(do_query "SHOW DATABASES;")
+    if [ $? -eq 0 ]; then
+        echo " ... Success!"
+    else
+        echo " ... Failed!  Not critical, keep moving..."
+    fi  
+}
+
 
 interrupt() {
     echo
@@ -416,6 +429,8 @@ echo
 get_root_password
 
 get_list_databases
+
+get_list_databases2
 
 cleanup
 
