fix error install nodejs

diff --git a/centos7/menu/developments/install_nodejs b/centos7/menu/developments/install_nodejs
--- a/centos7/menu/developments/install_nodejs
+++ b/centos7/menu/developments/install_nodejs
@@ -8,16 +8,68 @@ clear
 . /etc/server_admin/menu/verify_none_root
 . /etc/server_admin/menu/developments/common
 
-export NVM_DIR="$HOME/.nvm" && (
-  git clone https://github.com/creationix/nvm.git "$NVM_DIR"
-  cd "$NVM_DIR"
-  git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
-) && \. "$NVM_DIR/nvm.sh"
+nvm_install_dir() {
+	if [ -n "$NVM_DIR" ]; then
+	printf %s "${NVM_DIR}"
+	elif [ -n "$XDG_CONFIG_HOME" ]; then
+	printf %s "${XDG_CONFIG_HOME/nvm}"
+	else
+	printf %s "$HOME/.nvm"
+	fi
+}
 
-cat <<EOT >> ~/.bashrc
+update() {
+    command git --git-dir="$INSTALL_DIR"/.git --work-tree="$INSTALL_DIR" fetch origin tag "$(nvm_latest_version)" --depth=1 2> /dev/null || {
+      echo >&2 "Failed to update nvm, run 'git fetch' in $INSTALL_DIR yourself."
+      exit 1
+    } &&
+    PID=$!
+	i=1
+	sp="/-\|"
+	echo -e -n "${BGreen}NVM is already installed in $INSTALL_DIR, trying to update using git...${Color_Off} "
+	while [ -d /proc/$PID ]
+	do
+	  printf "\b${sp:i++%${#sp}:1}"
+	done
+	echo -e "${BBlue} Done${Color_Off}"
+	printf "\n"
+}
+
+install_new() {
+	export NVM_DIR="$HOME/.nvm" && (
+	  git clone https://github.com/creationix/nvm.git "$NVM_DIR"
+	  cd "$NVM_DIR"
+	  git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
+	) && \. "$NVM_DIR/nvm.sh" && (
+		cat <<EOT >> ~/.bashrc
 export NVM_DIR="$HOME/.nvm"
 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
 EOT
+) &&
+	PID=$!
+	i=1
+	sp="/-\|"
+	echo -e -n "${BGreen}Installing NVM...${Color_Off} "
+	while [ -d /proc/$PID ]
+	do
+	  printf "\b${sp:i++%${#sp}:1}"
+	done
+	echo -e "${BBlue} Done${Color_Off}"
+	printf "\n" 
+}
+
+install_nvm_from_git() {
+  local INSTALL_DIR
+  INSTALL_DIR="$(nvm_install_dir)"
+
+  if [ -d "$INSTALL_DIR/.git" ]; then
+    install_new
+  else
+    update
+  fi
+}
+
+install_nvm_from_git
 
 . $NVM_DIR/nvm.sh
 
