Fix error

diff --git a/centos7/menu/developments/restore_mysql_database b/centos7/menu/developments/restore_mysql_database
--- a/centos7/menu/developments/restore_mysql_database
+++ b/centos7/menu/developments/restore_mysql_database
@@ -413,6 +413,9 @@ restore_database(){
       show_menu "Chose database you want to restore" "${databases[@]}"
       choice=$?
       databaseName=${databases[$choice-1]};
+      if [ "$databaseName" == "Cancel" ]; then
+        back_to_menu
+      fi
       echo -n -e "Path to backup file: "
       read backupFile
       backupFileConvert=`echo $backupFile | sed -r "s/\~/\/home\/$logon_username/"`
@@ -422,34 +425,30 @@ restore_database(){
           cleanup
           back_to_menu
       else
-          if [ "$databaseName" == "Cancel" ]; then
+          mysqldump --defaults-file=$config --databases $databaseName < $backupFileConvert &
+          PID=$!
+          i=1
+          sp="/-\|"
+          echo -e -n "${BGreen}Restoring database: $databaseName${Color_Off} "
+          while [ -d /proc/$PID ]
+          do
+            printf "\b${sp:i++%${#sp}:1}"
+          done
+          printf "\n"
+          if [ $? -eq 0 ]; then
+              cleanup
+              clear
+              echo "===================================================================================="
+              echo -e "         ${BGreen} RESTORE DATABASE: $databaseName SUCCESSFUL${Color_Off}"
+              echo -e "         ${BBlue} From backup file: $backupFileName${Color_Off}"
+              echo "===================================================================================="
               back_to_menu
           else
-              mysqldump --defaults-file=$config --databases $databaseName < $backupFileConvert &
-              PID=$!
-              i=1
-              sp="/-\|"
-              echo -e -n "${BGreen}Restoring database: $databaseName${Color_Off} "
-              while [ -d /proc/$PID ]
-              do
-                printf "\b${sp:i++%${#sp}:1}"
-              done
-              printf "\n"
-              if [ $? -eq 0 ]; then
-                  cleanup
-                  clear
-                  echo "===================================================================================="
-                  echo -e "         ${BGreen} RESTORE DATABASE: $databaseName SUCCESSFUL${Color_Off}"
-                  echo -e "         ${BBlue} From backup file: $backupFileName${Color_Off}"
-                  echo "===================================================================================="
-                  back_to_menu
-              else
-                  echo "===================================================================================="
-                  echo -e "         ${BRed} RESTORE DATABASE: $databaseName ERROR${Color_Off}"
-                  echo -e "         ${BRed} From backup file: $backupFileName${Color_Off}"
-                  echo "===================================================================================="
-                  back_to_menu
-              fi
+              echo "===================================================================================="
+              echo -e "         ${BRed} RESTORE DATABASE: $databaseName ERROR${Color_Off}"
+              echo -e "         ${BRed} From backup file: $backupFileName${Color_Off}"
+              echo "===================================================================================="
+              back_to_menu
           fi
       fi      
   else
